<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623210340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE books (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(6) NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, is_borrowed BOOLEAN NOT NULL, current_borrower_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A1B2A92D948EE2 ON books (serial_number)');
        $this->addSql('CREATE INDEX IDX_4A1B2A92AF1A9AF2 ON books (current_borrower_id)');
        $this->addSql('CREATE TABLE employees (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, role VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE loan_histories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_id INT NOT NULL, user_id INT NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8EA2F23916A2B381 ON loan_histories (book_id)');
        $this->addSql('CREATE INDEX IDX_8EA2F239A76ED395 ON loan_histories (user_id)');
        $this->addSql('CREATE INDEX IDX_8EA2F2398C03F15C ON loan_histories (employee_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, card_number VARCHAR(6) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E4AF4C20 ON users (card_number)');
        $this->addSql('ALTER TABLE books ADD CONSTRAINT FK_4A1B2A92AF1A9AF2 FOREIGN KEY (current_borrower_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE loan_histories ADD CONSTRAINT FK_8EA2F23916A2B381 FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE loan_histories ADD CONSTRAINT FK_8EA2F239A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE loan_histories ADD CONSTRAINT FK_8EA2F2398C03F15C FOREIGN KEY (employee_id) REFERENCES employees (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE books DROP CONSTRAINT FK_4A1B2A92AF1A9AF2');
        $this->addSql('ALTER TABLE loan_histories DROP CONSTRAINT FK_8EA2F23916A2B381');
        $this->addSql('ALTER TABLE loan_histories DROP CONSTRAINT FK_8EA2F239A76ED395');
        $this->addSql('ALTER TABLE loan_histories DROP CONSTRAINT FK_8EA2F2398C03F15C');
        $this->addSql('DROP TABLE books');
        $this->addSql('DROP TABLE employees');
        $this->addSql('DROP TABLE loan_histories');
        $this->addSql('DROP TABLE users');
    }
}
